/**
 * Demo Conversations & Messages
 *
 * Realistic chat samples for testing.
 */

import type { NewConversation, NewMessage } from '../schema.js';
import { generateId, dateTimeFromNow } from './helpers.js';
import { demoGuests } from './guests.js';
import { demoReservations } from './reservations.js';

// Get checked-in reservations for active conversations
const checkedInReservations = demoReservations.filter((r) => r.status === 'checked_in');

// Conversation 1: Room service request (active)
const conv1Id = generateId();
const conv1Guest = demoGuests[3]!; // Mohammed Al-Rashid (VIP)
const conv1Reservation = checkedInReservations[0];

// Conversation 2: Housekeeping issue (escalated)
const conv2Id = generateId();
const conv2Guest = demoGuests[6]!; // Priya Sharma
const conv2Reservation = checkedInReservations[1];

// Conversation 3: Check-out inquiry (resolved)
const conv3Id = generateId();
const conv3Guest = demoGuests[0]!; // James Morrison (VIP)
const conv3Reservation = checkedInReservations[2];

// Conversation 4: Restaurant reservation (active)
const conv4Id = generateId();
const conv4Guest = demoGuests[1]!; // Sofia Garcia
const conv4Reservation = checkedInReservations[3];

// Conversation 5: Wifi issue (resolved)
const conv5Id = generateId();
const conv5Guest = demoGuests[8]!; // Chen Wei (VIP)
const conv5Reservation = checkedInReservations[4];

export const demoConversations: NewConversation[] = [
  {
    id: conv1Id,
    guestId: conv1Guest.id,
    reservationId: conv1Reservation?.id,
    channelType: 'whatsapp',
    channelId: conv1Guest.phone || '+971-50-123-4567',
    state: 'active',
    currentIntent: 'room_service',
    metadata: JSON.stringify({ vip: true }),
    lastMessageAt: dateTimeFromNow(0, 10),
    createdAt: dateTimeFromNow(-1, 14),
  },
  {
    id: conv2Id,
    guestId: conv2Guest.id,
    reservationId: conv2Reservation?.id,
    channelType: 'webchat',
    channelId: `session_${generateId().slice(0, 8)}`,
    state: 'escalated',
    currentIntent: 'complaint',
    metadata: JSON.stringify({ escalationReason: 'Guest dissatisfied with room cleanliness' }),
    lastMessageAt: dateTimeFromNow(0, 9),
    createdAt: dateTimeFromNow(0, 8),
  },
  {
    id: conv3Id,
    guestId: conv3Guest.id,
    reservationId: conv3Reservation?.id,
    channelType: 'sms',
    channelId: conv3Guest.phone || '+1-555-0101',
    state: 'resolved',
    currentIntent: 'checkout_info',
    metadata: JSON.stringify({ vip: true }),
    lastMessageAt: dateTimeFromNow(-1, 16),
    resolvedAt: dateTimeFromNow(-1, 16),
    createdAt: dateTimeFromNow(-1, 15),
  },
  {
    id: conv4Id,
    guestId: conv4Guest.id,
    reservationId: conv4Reservation?.id,
    channelType: 'whatsapp',
    channelId: conv4Guest.phone || '+34-612-345678',
    state: 'active',
    currentIntent: 'restaurant_booking',
    metadata: JSON.stringify({}),
    lastMessageAt: dateTimeFromNow(0, 11),
    createdAt: dateTimeFromNow(0, 11),
  },
  {
    id: conv5Id,
    guestId: conv5Guest.id,
    reservationId: conv5Reservation?.id,
    channelType: 'email',
    channelId: conv5Guest.email || 'chen.wei@email.com',
    state: 'resolved',
    currentIntent: 'wifi_support',
    metadata: JSON.stringify({ vip: true }),
    lastMessageAt: dateTimeFromNow(-2, 20),
    resolvedAt: dateTimeFromNow(-2, 20),
    createdAt: dateTimeFromNow(-2, 18),
  },
];

export const demoMessages: NewMessage[] = [
  // Conversation 1: Room service request
  {
    id: generateId(),
    conversationId: conv1Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv1Guest.id,
    content: 'Hello, I would like to order room service please',
    contentType: 'text',
    intent: 'room_service',
    confidence: 0.95,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 14),
  },
  {
    id: generateId(),
    conversationId: conv1Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'Good afternoon, Mr. Al-Rashid! I\'d be happy to help you with room service. Our menu includes breakfast items until 11 AM, lunch from 11 AM to 5 PM, and dinner from 5 PM onwards. What would you like to order today?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 14),
  },
  {
    id: generateId(),
    conversationId: conv1Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv1Guest.id,
    content: 'I would like the grilled salmon with vegetables and a bottle of sparkling water. Also, do you have any halal options for dessert?',
    contentType: 'text',
    intent: 'room_service',
    confidence: 0.92,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 14),
  },
  {
    id: generateId(),
    conversationId: conv1Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'Excellent choice! The grilled salmon with seasonal vegetables is one of our chef\'s specialties. For halal dessert options, I recommend our fresh fruit platter or the chocolate mousse - both are prepared in accordance with halal guidelines. Shall I add one of these to your order?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 14),
  },
  {
    id: generateId(),
    conversationId: conv1Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv1Guest.id,
    content: 'Yes, the chocolate mousse please. How long will it take?',
    contentType: 'text',
    intent: 'room_service',
    confidence: 0.88,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 10),
  },
  {
    id: generateId(),
    conversationId: conv1Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'I\'ve placed your order: grilled salmon with vegetables, sparkling water, and chocolate mousse. Your order will be delivered to suite 405 in approximately 35-40 minutes. Is there anything else I can help you with?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 10),
  },

  // Conversation 2: Housekeeping complaint (escalated)
  {
    id: generateId(),
    conversationId: conv2Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv2Guest.id,
    content: 'Hi, I checked into room 506 about an hour ago and the room hasn\'t been properly cleaned. There are used towels in the bathroom and the bed wasn\'t made.',
    contentType: 'text',
    intent: 'complaint',
    confidence: 0.89,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 8),
  },
  {
    id: generateId(),
    conversationId: conv2Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'I sincerely apologize for this inconvenience, Ms. Sharma. This is not the standard of cleanliness we strive for. I\'m immediately notifying our housekeeping supervisor to address this. Would you prefer to wait in our lobby lounge with a complimentary beverage while we prepare your room, or would you like us to move you to a different room?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 8),
  },
  {
    id: generateId(),
    conversationId: conv2Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv2Guest.id,
    content: 'This is really unacceptable. I\'ve stayed here before and never had this issue. I\'d like to speak with a manager.',
    contentType: 'text',
    intent: 'escalation_request',
    confidence: 0.94,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 9),
  },
  {
    id: generateId(),
    conversationId: conv2Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'I completely understand your frustration, and I apologize again. I\'m escalating this to our duty manager right away. They will contact you within the next 5 minutes to personally address your concerns and ensure we make this right.',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 9),
  },
  {
    id: generateId(),
    conversationId: conv2Id,
    direction: 'outbound',
    senderType: 'system',
    content: 'Conversation escalated to duty manager. Reason: Guest dissatisfied with room cleanliness, requesting manager.',
    contentType: 'text',
    deliveryStatus: 'sent',
    createdAt: dateTimeFromNow(0, 9),
  },

  // Conversation 3: Check-out inquiry (resolved)
  {
    id: generateId(),
    conversationId: conv3Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv3Guest.id,
    content: 'What time is checkout tomorrow?',
    contentType: 'text',
    intent: 'checkout_info',
    confidence: 0.97,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 15),
  },
  {
    id: generateId(),
    conversationId: conv3Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'Good afternoon, Mr. Morrison! Standard checkout time is 11:00 AM. As a Platinum member, you\'re entitled to complimentary late checkout until 2:00 PM when available. Would you like me to arrange late checkout for you?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 15),
  },
  {
    id: generateId(),
    conversationId: conv3Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv3Guest.id,
    content: 'Yes please, 2pm checkout would be great. Can you also arrange airport shuttle?',
    contentType: 'text',
    intent: 'checkout_info',
    confidence: 0.91,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 15),
  },
  {
    id: generateId(),
    conversationId: conv3Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'I\'ve arranged late checkout at 2:00 PM for you. For the airport shuttle, our complimentary service runs every 30 minutes. What time is your flight, and which terminal do you need?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 16),
  },
  {
    id: generateId(),
    conversationId: conv3Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv3Guest.id,
    content: 'Flight is at 5pm, Terminal 2',
    contentType: 'text',
    intent: 'transportation',
    confidence: 0.93,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 16),
  },
  {
    id: generateId(),
    conversationId: conv3Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'I\'ve scheduled the airport shuttle for 2:30 PM pickup at the main entrance for Terminal 2. This will give you plenty of time for check-in. Your late checkout and shuttle are all confirmed. Is there anything else you need for your departure?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 16),
  },
  {
    id: generateId(),
    conversationId: conv3Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv3Guest.id,
    content: 'That\'s all, thank you!',
    contentType: 'text',
    intent: 'gratitude',
    confidence: 0.96,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 16),
  },
  {
    id: generateId(),
    conversationId: conv3Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'You\'re welcome, Mr. Morrison! We hope you enjoyed your stay. Have a safe flight, and we look forward to welcoming you back soon!',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-1, 16),
  },

  // Conversation 4: Restaurant reservation (active)
  {
    id: generateId(),
    conversationId: conv4Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv4Guest.id,
    content: 'Hola! Can I make a dinner reservation for tonight?',
    contentType: 'text',
    intent: 'restaurant_booking',
    confidence: 0.94,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 11),
  },
  {
    id: generateId(),
    conversationId: conv4Id,
    direction: 'outbound',
    senderType: 'ai',
    content: '¡Hola, Ms. Garcia! I\'d be happy to help you with a dinner reservation. Our main restaurant, The Garden, serves dinner from 6:00 PM to 10:00 PM. How many guests will be dining, and what time would you prefer?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 11),
  },
  {
    id: generateId(),
    conversationId: conv4Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv4Guest.id,
    content: '2 people at 8pm please. Do they have vegetarian options?',
    contentType: 'text',
    intent: 'restaurant_booking',
    confidence: 0.91,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 11),
  },
  {
    id: generateId(),
    conversationId: conv4Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'Great! Yes, The Garden has excellent vegetarian options including a roasted vegetable risotto and a Mediterranean mezze platter. I\'ve reserved a table for 2 at 8:00 PM under Garcia, room 407. Would you like a table by the window or in the main dining area?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(0, 11),
  },

  // Conversation 5: WiFi issue (resolved)
  {
    id: generateId(),
    conversationId: conv5Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv5Guest.id,
    content: 'The WiFi in my room keeps disconnecting. I need stable internet for a video conference tomorrow morning.',
    contentType: 'text',
    intent: 'wifi_support',
    confidence: 0.92,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-2, 18),
  },
  {
    id: generateId(),
    conversationId: conv5Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'I apologize for the inconvenience, Mr. Wei. Let me help you troubleshoot this. First, could you try forgetting the "HotelGuest" network on your device and reconnecting? Also, may I ask which room you\'re in so I can check if there are any known issues in that area?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-2, 18),
  },
  {
    id: generateId(),
    conversationId: conv5Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv5Guest.id,
    content: 'I\'m in room 609. I tried reconnecting but it keeps dropping after a few minutes.',
    contentType: 'text',
    intent: 'wifi_support',
    confidence: 0.89,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-2, 19),
  },
  {
    id: generateId(),
    conversationId: conv5Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'Thank you for the details. I\'ve alerted our IT team about the connectivity issues on floor 6. In the meantime, I can offer you a portable WiFi hotspot device for your conference tomorrow. It provides dedicated high-speed connection. Should I have one delivered to your room?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-2, 19),
  },
  {
    id: generateId(),
    conversationId: conv5Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv5Guest.id,
    content: 'Yes please, that would be very helpful. Thank you.',
    contentType: 'text',
    intent: 'confirmation',
    confidence: 0.95,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-2, 20),
  },
  {
    id: generateId(),
    conversationId: conv5Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'A portable WiFi hotspot will be delivered to room 609 within 15 minutes. The device comes pre-configured - simply power it on and connect to the network shown on the label. It offers speeds up to 150 Mbps, perfect for video conferencing. Is there anything else I can help you with?',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-2, 20),
  },
  {
    id: generateId(),
    conversationId: conv5Id,
    direction: 'inbound',
    senderType: 'guest',
    senderId: conv5Guest.id,
    content: 'No that\'s all. Thanks for the quick help!',
    contentType: 'text',
    intent: 'gratitude',
    confidence: 0.97,
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-2, 20),
  },
  {
    id: generateId(),
    conversationId: conv5Id,
    direction: 'outbound',
    senderType: 'ai',
    content: 'You\'re welcome! Good luck with your conference tomorrow. Don\'t hesitate to reach out if you need anything else.',
    contentType: 'text',
    deliveryStatus: 'delivered',
    createdAt: dateTimeFromNow(-2, 20),
  },
];
