/**
 * Demo Guests
 *
 * 10 realistic guest profiles with varied nationalities, languages, and loyalty tiers.
 */

import type { NewGuest } from '../schema.js';
import { generateId } from './helpers.js';

export const demoGuests: NewGuest[] = [
  {
    id: generateId(),
    firstName: 'James',
    lastName: 'Morrison',
    email: 'james.morrison@email.com',
    phone: '+1-555-0101',
    language: 'en',
    loyaltyTier: 'platinum',
    vipStatus: 'vip',
    stayCount: 12,
    totalRevenue: 15420.0,
    notes: 'Prefers high floor, quiet room. Regular business traveler.',
  },
  {
    id: generateId(),
    firstName: 'Sofia',
    lastName: 'Garcia',
    email: 'sofia.garcia@email.com',
    phone: '+34-612-345678',
    language: 'es',
    loyaltyTier: 'gold',
    vipStatus: null,
    stayCount: 5,
    totalRevenue: 4280.0,
    notes: 'Allergic to feather pillows.',
  },
  {
    id: generateId(),
    firstName: 'Yuki',
    lastName: 'Tanaka',
    email: 'yuki.tanaka@email.com',
    phone: '+81-90-1234-5678',
    language: 'ja',
    loyaltyTier: 'silver',
    vipStatus: null,
    stayCount: 3,
    totalRevenue: 2150.0,
  },
  {
    id: generateId(),
    firstName: 'Mohammed',
    lastName: 'Al-Rashid',
    email: 'mohammed.alrashid@email.com',
    phone: '+971-50-123-4567',
    language: 'ar',
    loyaltyTier: 'platinum',
    vipStatus: 'vip',
    stayCount: 8,
    totalRevenue: 28500.0,
    notes: 'Suite preference. Halal dietary requirements.',
  },
  {
    id: generateId(),
    firstName: 'Emma',
    lastName: 'Thompson',
    email: 'emma.thompson@email.com',
    phone: '+44-7700-900123',
    language: 'en',
    loyaltyTier: null,
    vipStatus: null,
    stayCount: 1,
    totalRevenue: 890.0,
  },
  {
    id: generateId(),
    firstName: 'Hans',
    lastName: 'Mueller',
    email: 'hans.mueller@email.com',
    phone: '+49-170-1234567',
    language: 'de',
    loyaltyTier: 'gold',
    vipStatus: null,
    stayCount: 6,
    totalRevenue: 5640.0,
    notes: 'Early riser, requests early breakfast.',
  },
  {
    id: generateId(),
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@email.com',
    phone: '+91-98765-43210',
    language: 'hi',
    loyaltyTier: 'silver',
    vipStatus: null,
    stayCount: 4,
    totalRevenue: 3200.0,
    notes: 'Vegetarian. Prefers rooms away from elevator.',
  },
  {
    id: generateId(),
    firstName: 'Pierre',
    lastName: 'Dubois',
    email: 'pierre.dubois@email.com',
    phone: '+33-6-12-34-56-78',
    language: 'fr',
    loyaltyTier: null,
    vipStatus: null,
    stayCount: 2,
    totalRevenue: 1560.0,
  },
  {
    id: generateId(),
    firstName: 'Chen',
    lastName: 'Wei',
    email: 'chen.wei@email.com',
    phone: '+86-138-1234-5678',
    language: 'zh',
    loyaltyTier: 'gold',
    vipStatus: 'vip',
    stayCount: 7,
    totalRevenue: 12800.0,
    notes: 'Corporate account. Requires receipts for all charges.',
  },
  {
    id: generateId(),
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'maria.santos@email.com',
    phone: '+55-11-98765-4321',
    language: 'pt',
    loyaltyTier: 'silver',
    vipStatus: null,
    stayCount: 3,
    totalRevenue: 2340.0,
  },
];
