/**
 * Demo Knowledge Base
 *
 * 100 entries covering hotel FAQs, policies, amenities, services, and local info.
 */

import type { NewKnowledgeItem } from '../schema.js';
import { generateId } from './helpers.js';

export const demoKnowledgeBase: NewKnowledgeItem[] = [
  // Check-in/Check-out (5)
  {
    id: generateId(),
    category: 'policy',
    title: 'Check-in Time',
    content: 'Standard check-in time is 3:00 PM. Early check-in may be available upon request and subject to availability. Please contact the front desk to arrange early arrival.',
    keywords: JSON.stringify(['check-in', 'arrival', 'time', 'early check-in']),
    priority: 10,
  },
  {
    id: generateId(),
    category: 'policy',
    title: 'Check-out Time',
    content: 'Check-out time is 11:00 AM. Late check-out until 2:00 PM is available for $50. Later departures may be charged a full night rate. Please arrange at the front desk.',
    keywords: JSON.stringify(['check-out', 'departure', 'time', 'late check-out']),
    priority: 10,
  },
  {
    id: generateId(),
    category: 'policy',
    title: 'Express Check-out',
    content: 'Express check-out is available. Simply drop your key card in the express check-out box at the front desk. Your receipt will be emailed to the address on file within 24 hours.',
    keywords: JSON.stringify(['express', 'check-out', 'quick', 'key drop']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Early Check-in Availability',
    content: 'Early check-in is complimentary for our Platinum and Gold loyalty members when rooms are available. Other guests may request early check-in for a fee of $30, subject to availability.',
    keywords: JSON.stringify(['early', 'check-in', 'loyalty', 'complimentary']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Luggage Storage',
    content: 'Complimentary luggage storage is available for guests arriving early or departing late. Simply bring your bags to the bell desk and we will securely store them until you need them.',
    keywords: JSON.stringify(['luggage', 'storage', 'bags', 'bell desk']),
    priority: 5,
  },

  // Room Types (10)
  {
    id: generateId(),
    category: 'room_type',
    title: 'Standard King Room',
    content: 'Our Standard King rooms feature a plush king-size bed, 42-inch flat-screen TV, work desk, mini-fridge, coffee maker, and complimentary WiFi. Room size is approximately 300 sq ft.',
    keywords: JSON.stringify(['standard', 'king', 'room', 'bed']),
    priority: 8,
  },
  {
    id: generateId(),
    category: 'room_type',
    title: 'Standard Queen Room',
    content: 'Standard Queen rooms offer one queen-size bed, perfect for solo travelers or couples. Amenities include 42-inch TV, work desk, mini-fridge, and complimentary WiFi. Room size is 280 sq ft.',
    keywords: JSON.stringify(['standard', 'queen', 'room', 'single']),
    priority: 8,
  },
  {
    id: generateId(),
    category: 'room_type',
    title: 'Deluxe King Room',
    content: 'Deluxe King rooms provide extra space at 380 sq ft with premium bedding, a seating area, 50-inch smart TV, Nespresso machine, and enhanced bathroom amenities including a rain shower.',
    keywords: JSON.stringify(['deluxe', 'king', 'premium', 'spacious']),
    priority: 8,
  },
  {
    id: generateId(),
    category: 'room_type',
    title: 'Junior Suite',
    content: 'Our Junior Suites offer 450 sq ft of luxury with a separate living area, king bed, soaking tub, walk-in rain shower, 55-inch smart TV, and stunning city views.',
    keywords: JSON.stringify(['junior', 'suite', 'living area', 'luxury']),
    priority: 8,
  },
  {
    id: generateId(),
    category: 'room_type',
    title: 'Executive Suite',
    content: 'The Executive Suite spans 650 sq ft with a full living room, dining area, king bedroom, marble bathroom with soaking tub, premium amenities, and panoramic views. Includes executive lounge access.',
    keywords: JSON.stringify(['executive', 'suite', 'lounge', 'panoramic']),
    priority: 9,
  },
  {
    id: generateId(),
    category: 'room_type',
    title: 'Connecting Rooms',
    content: 'Connecting rooms are available for families or groups traveling together. Please request at booking or contact reservations. Subject to availability.',
    keywords: JSON.stringify(['connecting', 'family', 'adjoining', 'group']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'room_type',
    title: 'Accessible Rooms',
    content: 'Wheelchair accessible rooms are available with roll-in showers, grab bars, lowered fixtures, and visual alerts. Please specify accessibility needs when booking.',
    keywords: JSON.stringify(['accessible', 'wheelchair', 'ADA', 'disability']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'In-Room Safe',
    content: 'All rooms include a personal electronic safe large enough for a laptop computer. Instructions are on the safe or contact the front desk for assistance.',
    keywords: JSON.stringify(['safe', 'security', 'valuables', 'laptop']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Mini Bar',
    content: 'Deluxe rooms and suites feature a stocked mini bar. Items consumed will be charged to your room. A menu with prices is available in the mini bar cabinet.',
    keywords: JSON.stringify(['mini bar', 'drinks', 'snacks', 'beverages']),
    priority: 3,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Room Service Menu',
    content: 'Room service is available 24 hours. Breakfast is served 6 AM - 11 AM, lunch 11 AM - 5 PM, dinner 5 PM - 11 PM, and a late-night menu is available 11 PM - 6 AM.',
    keywords: JSON.stringify(['room service', 'menu', 'hours', 'dining']),
    priority: 6,
  },

  // Restaurant (8)
  {
    id: generateId(),
    category: 'service',
    title: 'Main Restaurant - The Garden',
    content: 'The Garden restaurant serves breakfast, lunch, and dinner. Located on the lobby level. Breakfast 6:30 AM - 10:30 AM, Lunch 12:00 PM - 2:30 PM, Dinner 6:00 PM - 10:00 PM.',
    keywords: JSON.stringify(['restaurant', 'garden', 'breakfast', 'dinner', 'lunch']),
    priority: 8,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Breakfast Buffet',
    content: 'Our breakfast buffet features fresh pastries, made-to-order eggs, seasonal fruits, cereals, yogurt, and hot items. Price is $32 per adult, $16 for children under 12.',
    keywords: JSON.stringify(['breakfast', 'buffet', 'eggs', 'pastries']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Rooftop Bar - Sky Lounge',
    content: 'Sky Lounge offers craft cocktails and small plates with panoramic city views. Open Tuesday - Sunday, 5 PM - midnight. Smart casual dress code. Reservations recommended on weekends.',
    keywords: JSON.stringify(['bar', 'rooftop', 'cocktails', 'sky lounge', 'drinks']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Lobby Cafe',
    content: 'The Lobby Cafe serves Starbucks coffee, fresh pastries, sandwiches, and light snacks from 6 AM to 8 PM daily. Grab-and-go options available.',
    keywords: JSON.stringify(['cafe', 'coffee', 'starbucks', 'snacks', 'lobby']),
    priority: 6,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Restaurant Reservations',
    content: 'Restaurant reservations can be made through the concierge, by calling extension 4500, or through the hotel app. We recommend reservations for dinner and weekend brunch.',
    keywords: JSON.stringify(['reservation', 'booking', 'restaurant', 'table']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Dietary Requirements',
    content: 'Our chefs accommodate vegetarian, vegan, gluten-free, halal, and kosher dietary requirements. Please inform your server or note requirements when making reservations.',
    keywords: JSON.stringify(['vegetarian', 'vegan', 'gluten-free', 'halal', 'kosher', 'allergy']),
    priority: 6,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Private Dining',
    content: 'Private dining rooms are available for groups of 8-40 guests. Contact our events team at extension 4600 or events@hotel.com for menus and availability.',
    keywords: JSON.stringify(['private', 'dining', 'events', 'group', 'party']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'In-Room Dining',
    content: 'In-room dining is available 24 hours. View the menu on your TV or in the room directory. Dial 0 to place an order. A 20% service charge and delivery fee applies.',
    keywords: JSON.stringify(['in-room', 'dining', 'delivery', 'food']),
    priority: 6,
  },

  // Spa & Wellness (6)
  {
    id: generateId(),
    category: 'service',
    title: 'Spa Hours',
    content: 'The Serenity Spa is open daily from 9 AM to 9 PM. Treatments include massage, facials, body wraps, and nail services. Advance booking recommended. Call extension 5000.',
    keywords: JSON.stringify(['spa', 'hours', 'massage', 'wellness']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Spa Treatments',
    content: 'Popular treatments include our signature 60-minute massage ($150), deep tissue massage ($170), aromatherapy facial ($130), and couples massage packages starting at $280.',
    keywords: JSON.stringify(['spa', 'massage', 'facial', 'treatment', 'couples']),
    priority: 6,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Spa Cancellation',
    content: 'Spa appointments must be cancelled at least 4 hours in advance to avoid a 50% cancellation fee. No-shows will be charged the full treatment price.',
    keywords: JSON.stringify(['spa', 'cancellation', 'policy', 'appointment']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Sauna and Steam Room',
    content: 'Complimentary sauna and steam room are located in the spa area. Open 6 AM - 10 PM for hotel guests. Towels are provided. Please shower before use.',
    keywords: JSON.stringify(['sauna', 'steam', 'spa', 'complimentary']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Salon Services',
    content: 'The salon offers haircuts, styling, manicures, pedicures, and makeup services. Perfect for special occasions. Appointments available daily 10 AM - 7 PM.',
    keywords: JSON.stringify(['salon', 'hair', 'nails', 'manicure', 'pedicure']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Spa Packages',
    content: 'Day spa packages include facility access, robe and slippers, and a wellness lunch. Half-day package $299, full-day package $449. Perfect for a gift.',
    keywords: JSON.stringify(['spa', 'package', 'gift', 'day spa']),
    priority: 5,
  },

  // Pool & Fitness (4)
  {
    id: generateId(),
    category: 'amenity',
    title: 'Swimming Pool',
    content: 'The outdoor pool is open daily 7 AM - 10 PM from May through September. Towels, loungers, and umbrellas provided. Pool bar serves drinks and light fare.',
    keywords: JSON.stringify(['pool', 'swimming', 'outdoor', 'towels']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Fitness Center',
    content: 'Our 24-hour fitness center features cardio equipment, free weights, and strength machines. Complimentary for all guests. Personal training available upon request ($80/hour).',
    keywords: JSON.stringify(['gym', 'fitness', 'exercise', 'weights', '24-hour']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Pool Depth',
    content: 'The main pool ranges from 3.5 feet to 5.5 feet deep. A separate children\'s wading pool is 1.5 feet deep. Lifeguard on duty during peak hours.',
    keywords: JSON.stringify(['pool', 'depth', 'children', 'lifeguard']),
    priority: 3,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Yoga Classes',
    content: 'Complimentary yoga classes are offered poolside at 7 AM on weekdays and 8 AM on weekends. Mats provided. Sign up at the fitness center or concierge.',
    keywords: JSON.stringify(['yoga', 'class', 'exercise', 'fitness', 'free']),
    priority: 4,
  },

  // WiFi & Business (4)
  {
    id: generateId(),
    category: 'amenity',
    title: 'WiFi Access',
    content: 'Complimentary high-speed WiFi is available throughout the hotel. Connect to "HotelGuest" network and enter your room number and last name to access.',
    keywords: JSON.stringify(['wifi', 'internet', 'wireless', 'free']),
    priority: 9,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'WiFi Troubleshooting',
    content: 'If you experience WiFi issues, try forgetting the network and reconnecting. For persistent issues, contact IT support at extension 8000 or visit the business center.',
    keywords: JSON.stringify(['wifi', 'problem', 'connection', 'support']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Business Center',
    content: 'The business center on the lobby level offers computers, printing, scanning, and faxing. Open 24 hours. Printing is $0.25/page B&W, $1.00/page color.',
    keywords: JSON.stringify(['business center', 'printing', 'computer', 'fax']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Meeting Rooms',
    content: 'Meeting rooms accommodate 2-200 guests with AV equipment, catering, and dedicated event support. Contact events@hotel.com or extension 4600 for availability and pricing.',
    keywords: JSON.stringify(['meeting', 'conference', 'room', 'events', 'AV']),
    priority: 5,
  },

  // Parking & Transportation (6)
  {
    id: generateId(),
    category: 'service',
    title: 'Parking Options',
    content: 'Self-parking is $25/night, valet parking is $40/night. Both include in-and-out privileges. Electric vehicle charging stations available in the garage.',
    keywords: JSON.stringify(['parking', 'valet', 'car', 'garage', 'EV']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Airport Shuttle',
    content: 'Complimentary airport shuttle runs every 30 minutes from 5 AM to 11 PM. Pick up at the main entrance. Call the bell desk when you land and we\'ll have a shuttle waiting.',
    keywords: JSON.stringify(['airport', 'shuttle', 'transportation', 'free']),
    priority: 8,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Taxi and Rideshare',
    content: 'Taxis are available at the main entrance. The bell desk can call a taxi or help arrange Uber/Lyft. Average ride to airport is $35-45.',
    keywords: JSON.stringify(['taxi', 'uber', 'lyft', 'rideshare', 'car']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Car Rental',
    content: 'Car rental services from Hertz and Enterprise are available through the concierge. Vehicles can be delivered to the hotel entrance.',
    keywords: JSON.stringify(['car rental', 'hertz', 'enterprise', 'vehicle']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Electric Vehicle Charging',
    content: 'Four Tesla Superchargers and two universal EV chargers are located on parking level P1. Charging is complimentary for hotel guests. First come, first served.',
    keywords: JSON.stringify(['EV', 'electric', 'charging', 'tesla']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Public Transportation',
    content: 'The Metro station is a 5-minute walk from the hotel. Bus stops are directly in front. The concierge can provide transit maps and day passes.',
    keywords: JSON.stringify(['metro', 'bus', 'transit', 'public transportation']),
    priority: 5,
  },

  // Housekeeping (4)
  {
    id: generateId(),
    category: 'service',
    title: 'Housekeeping Schedule',
    content: 'Daily housekeeping is provided between 9 AM and 4 PM. Place the "Make Up Room" sign on your door or request a specific time at the front desk.',
    keywords: JSON.stringify(['housekeeping', 'cleaning', 'maid', 'schedule']),
    priority: 6,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Extra Towels and Amenities',
    content: 'For extra towels, pillows, blankets, or toiletries, contact housekeeping at extension 3000 or press the housekeeping button on your phone. Items arrive within 15 minutes.',
    keywords: JSON.stringify(['towels', 'pillows', 'amenities', 'extra']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Do Not Disturb',
    content: 'Use the DND indicator on your door or enable it via the room panel. If DND is displayed past 2 PM, housekeeping will contact you to arrange service.',
    keywords: JSON.stringify(['do not disturb', 'DND', 'privacy']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'policy',
    title: 'Green Program',
    content: 'Help us conserve resources. Hang towels to reuse them, place on floor for replacement. Decline daily housekeeping for a $10 credit per night to your account.',
    keywords: JSON.stringify(['green', 'environment', 'towels', 'sustainability']),
    priority: 3,
  },

  // Policies (6)
  {
    id: generateId(),
    category: 'policy',
    title: 'Pet Policy',
    content: 'We welcome dogs under 50 lbs with a $75 non-refundable pet fee. Maximum 2 pets per room. Pets must be leashed in public areas. Dog walking service available.',
    keywords: JSON.stringify(['pet', 'dog', 'animal', 'policy']),
    priority: 6,
  },
  {
    id: generateId(),
    category: 'policy',
    title: 'Smoking Policy',
    content: 'The hotel is 100% smoke-free including e-cigarettes and vaping. A $250 deep cleaning fee applies for smoking in rooms. Designated smoking area outside the main entrance.',
    keywords: JSON.stringify(['smoking', 'vaping', 'smoke-free', 'policy']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'policy',
    title: 'Cancellation Policy',
    content: 'Free cancellation up to 24 hours before arrival. Cancellations within 24 hours or no-shows are charged one night\'s room rate. Prepaid rates are non-refundable.',
    keywords: JSON.stringify(['cancellation', 'cancel', 'refund', 'policy']),
    priority: 8,
  },
  {
    id: generateId(),
    category: 'policy',
    title: 'Payment Methods',
    content: 'We accept Visa, Mastercard, American Express, Discover, and debit cards. A credit card authorization for incidentals is required at check-in.',
    keywords: JSON.stringify(['payment', 'credit card', 'visa', 'mastercard']),
    priority: 6,
  },
  {
    id: generateId(),
    category: 'policy',
    title: 'Quiet Hours',
    content: 'Quiet hours are from 10 PM to 8 AM. Please be considerate of other guests. Contact security at extension 9000 if you experience noise disturbances.',
    keywords: JSON.stringify(['quiet', 'hours', 'noise', 'policy']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'policy',
    title: 'Damage Policy',
    content: 'Guests are responsible for any damage to hotel property during their stay. Charges will be applied to the credit card on file after assessment.',
    keywords: JSON.stringify(['damage', 'policy', 'liability']),
    priority: 3,
  },

  // Concierge Services (5)
  {
    id: generateId(),
    category: 'service',
    title: 'Concierge Desk',
    content: 'Our concierge team is available 7 AM - 11 PM to assist with restaurant reservations, tickets, tours, and local recommendations. Dial 0 or visit the lobby.',
    keywords: JSON.stringify(['concierge', 'help', 'assistance', 'recommendations']),
    priority: 7,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Ticket Services',
    content: 'The concierge can arrange tickets for theater, concerts, sports events, and local attractions. Book early for popular shows. Service fees may apply.',
    keywords: JSON.stringify(['tickets', 'theater', 'concerts', 'events', 'shows']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Tour Arrangements',
    content: 'Half-day and full-day city tours available through our concierge. Private guides and custom itineraries can be arranged with advance notice.',
    keywords: JSON.stringify(['tour', 'guide', 'sightseeing', 'city tour']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Flower Delivery',
    content: 'Surprise someone special with flowers delivered to their room. Arrangements from $50. Order through the concierge with at least 4 hours notice.',
    keywords: JSON.stringify(['flowers', 'delivery', 'gift', 'surprise']),
    priority: 3,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Special Occasions',
    content: 'Celebrating a birthday, anniversary, or special event? Let the concierge arrange in-room decorations, cake, champagne, or special dining experiences.',
    keywords: JSON.stringify(['birthday', 'anniversary', 'celebration', 'special']),
    priority: 4,
  },

  // Laundry (3)
  {
    id: generateId(),
    category: 'service',
    title: 'Laundry Service',
    content: 'Same-day laundry and dry cleaning available if received by 9 AM. Express 4-hour service available for 50% surcharge. Laundry bags in your closet.',
    keywords: JSON.stringify(['laundry', 'dry cleaning', 'clothes', 'pressing']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Laundry Prices',
    content: 'Shirt laundering $8, suit dry cleaning $25, dress dry cleaning $20, pants pressing $10. Full price list in the laundry bag or on the in-room TV.',
    keywords: JSON.stringify(['laundry', 'prices', 'cost', 'dry cleaning']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Self-Service Laundry',
    content: 'A self-service laundry room is located on the 3rd floor. Washers $3, dryers $2.50. Open 24 hours. Detergent available from vending machine.',
    keywords: JSON.stringify(['self-service', 'laundry', 'washer', 'dryer']),
    priority: 3,
  },

  // Safety & Security (4)
  {
    id: generateId(),
    category: 'policy',
    title: 'Emergency Procedures',
    content: 'In case of emergency, dial 911 or extension 9000 for hotel security. Emergency exits are marked with illuminated signs. Review the evacuation map on your door.',
    keywords: JSON.stringify(['emergency', 'fire', 'safety', 'evacuation']),
    priority: 8,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Lost and Found',
    content: 'For lost items, contact the front desk or email lostandfound@hotel.com. Found items are held for 90 days. Shipping can be arranged for a fee.',
    keywords: JSON.stringify(['lost', 'found', 'missing', 'items']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Room Safe',
    content: 'Your room includes a personal safe. Set a 4-digit code to secure valuables. If you forget your code, contact the front desk with valid ID.',
    keywords: JSON.stringify(['safe', 'security', 'valuables', 'code']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Security Cameras',
    content: 'For your safety, security cameras monitor all public areas including lobbies, hallways, and parking areas. Security staff is on duty 24/7.',
    keywords: JSON.stringify(['security', 'cameras', 'safety', 'CCTV']),
    priority: 3,
  },

  // Accessibility (4)
  {
    id: generateId(),
    category: 'amenity',
    title: 'Wheelchair Access',
    content: 'The hotel is fully wheelchair accessible with ramps, automatic doors, and accessible elevators. Wheelchair rental available through the concierge.',
    keywords: JSON.stringify(['wheelchair', 'accessible', 'disability', 'ramp']),
    priority: 6,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Visual Impairment Assistance',
    content: 'Braille signage throughout the hotel. Large-print menus and materials available upon request. Guide dogs welcome in all areas.',
    keywords: JSON.stringify(['braille', 'visual', 'blind', 'guide dog']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Hearing Impairment Assistance',
    content: 'Rooms with visual alert systems available. TTY/TDD devices and closed-caption TVs provided upon request. Staff trained in basic sign language.',
    keywords: JSON.stringify(['hearing', 'deaf', 'TTY', 'visual alert']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Service Animals',
    content: 'Service animals are welcome throughout the hotel at no additional charge. Please inform the front desk of your service animal for appropriate room placement.',
    keywords: JSON.stringify(['service animal', 'dog', 'disability', 'guide']),
    priority: 4,
  },

  // Local Attractions (10)
  {
    id: generateId(),
    category: 'local_info',
    title: 'Downtown Shopping',
    content: 'The downtown shopping district is a 10-minute walk from the hotel. Features luxury boutiques, department stores, and unique local shops. Open 10 AM - 9 PM.',
    keywords: JSON.stringify(['shopping', 'downtown', 'stores', 'boutique']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'City Museum',
    content: 'The City Art Museum is 15 minutes away by taxi. Open Tuesday-Sunday 10 AM - 5 PM. Adult admission $20, free on first Sunday of each month.',
    keywords: JSON.stringify(['museum', 'art', 'culture', 'attraction']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Historic District',
    content: 'The historic district with 18th-century architecture is a 20-minute walk. Free walking tours depart from the visitor center at 10 AM and 2 PM daily.',
    keywords: JSON.stringify(['historic', 'walking tour', 'architecture', 'sightseeing']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'City Park',
    content: 'City Park features 300 acres of gardens, walking trails, and a lake with boat rentals. 10-minute drive or 25-minute walk. Free admission.',
    keywords: JSON.stringify(['park', 'nature', 'walking', 'garden']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Theater District',
    content: 'The theater district is a 5-minute taxi ride with Broadway shows, concerts, and comedy clubs. Concierge can arrange tickets and dinner packages.',
    keywords: JSON.stringify(['theater', 'broadway', 'shows', 'entertainment']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Sports Venues',
    content: 'The stadium is 20 minutes by metro. Home to professional baseball (April-October) and football (September-January). Tickets available through concierge.',
    keywords: JSON.stringify(['sports', 'stadium', 'baseball', 'football']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Waterfront Area',
    content: 'The waterfront promenade features restaurants, bars, and scenic views. 15-minute walk along the river. Boat tours depart hourly from Pier 5.',
    keywords: JSON.stringify(['waterfront', 'river', 'boats', 'promenade']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Farmers Market',
    content: 'The Saturday farmers market runs 8 AM - 2 PM in Central Square, a 10-minute walk. Local produce, crafts, and food vendors. Rain or shine.',
    keywords: JSON.stringify(['farmers market', 'local', 'food', 'saturday']),
    priority: 3,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Nightlife',
    content: 'The entertainment district offers bars, clubs, and live music venues. Most active Thursday-Saturday. The concierge can recommend venues based on your preferences.',
    keywords: JSON.stringify(['nightlife', 'bars', 'clubs', 'music']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Day Trips',
    content: 'Popular day trips include wine country (1 hour), beach towns (45 minutes), and mountain hiking (1.5 hours). The concierge can arrange transportation and tours.',
    keywords: JSON.stringify(['day trip', 'wine', 'beach', 'hiking']),
    priority: 4,
  },

  // Nearby Restaurants (5)
  {
    id: generateId(),
    category: 'local_info',
    title: 'Fine Dining Nearby',
    content: 'Michelin-starred Restaurant Laurent is a 5-minute walk. Reservations essential. The concierge has a direct line for preferred booking. Dress code: business casual.',
    keywords: JSON.stringify(['fine dining', 'michelin', 'restaurant', 'upscale']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Casual Dining Options',
    content: 'Within walking distance: Mario\'s Italian (3 min), Green Bowl salads (5 min), Burger Joint (7 min), Sakura sushi (10 min). Maps available at concierge.',
    keywords: JSON.stringify(['casual', 'dining', 'restaurants', 'nearby']),
    priority: 5,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Late Night Dining',
    content: 'For late night food: City Diner (24 hours, 5 min walk), Dragon Palace Chinese (until 2 AM, 8 min), or room service is available 24/7.',
    keywords: JSON.stringify(['late night', 'dining', '24 hour', 'food']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Breakfast Spots',
    content: 'Besides our restaurant: Blue Bird Cafe (great pastries, 3 min), Sunny Side diner (classic American, 5 min), Juice Bar (healthy options, 4 min).',
    keywords: JSON.stringify(['breakfast', 'cafe', 'morning', 'coffee']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Food Delivery',
    content: 'DoorDash, Uber Eats, and Grubhub all deliver to the hotel. Give the front desk your name and room number as the delivery address.',
    keywords: JSON.stringify(['delivery', 'doordash', 'uber eats', 'food']),
    priority: 4,
  },

  // Weather & Visit Info (2)
  {
    id: generateId(),
    category: 'local_info',
    title: 'Weather and Seasons',
    content: 'Summers are warm (75-90°F), winters mild (40-55°F). Rainy season is November-March. Pack layers year-round. Umbrellas available at the bell desk.',
    keywords: JSON.stringify(['weather', 'temperature', 'season', 'climate']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'local_info',
    title: 'Best Time to Visit',
    content: 'Peak season is May-September with warm weather and outdoor events. Off-peak November-February offers lower rates and fewer crowds. Spring has beautiful gardens.',
    keywords: JSON.stringify(['best time', 'visit', 'season', 'peak']),
    priority: 3,
  },

  // Hotel Info (2)
  {
    id: generateId(),
    category: 'faq',
    title: 'Hotel History',
    content: 'Originally built in 1925 as a grand railway hotel, our property has been beautifully restored and modernized while maintaining its historic charm and architectural details.',
    keywords: JSON.stringify(['history', 'about', 'hotel', 'heritage']),
    priority: 2,
  },
  {
    id: generateId(),
    category: 'faq',
    title: 'Awards and Recognition',
    content: 'Proud recipient of AAA Four Diamond Award, TripAdvisor Certificate of Excellence, and Forbes Travel Guide Recommended. Committed to exceptional guest experiences.',
    keywords: JSON.stringify(['awards', 'rating', 'recognition', 'stars']),
    priority: 2,
  },

  // Additional Services (6)
  {
    id: generateId(),
    category: 'service',
    title: 'Babysitting Services',
    content: 'Licensed, bonded babysitters available with 24-hour advance notice. Rate is $25/hour with a 4-hour minimum. Contact concierge to arrange.',
    keywords: JSON.stringify(['babysitting', 'childcare', 'kids', 'children']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Ice Machine',
    content: 'Ice machines are located on every floor near the elevators. Ice buckets are in your room. For a bucket of ice delivered, contact room service.',
    keywords: JSON.stringify(['ice', 'ice machine', 'bucket']),
    priority: 2,
  },
  {
    id: generateId(),
    category: 'amenity',
    title: 'Vending Machines',
    content: 'Snack and beverage vending machines are located on floors 3, 6, and 9 near the ice machines. Accepts credit cards and mobile pay.',
    keywords: JSON.stringify(['vending', 'snacks', 'drinks', 'machine']),
    priority: 2,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Currency Exchange',
    content: 'Currency exchange services available at the front desk for major currencies. Rates posted daily. ATM in the lobby accepts international cards.',
    keywords: JSON.stringify(['currency', 'exchange', 'money', 'ATM']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Package Receiving',
    content: 'The hotel accepts packages on behalf of guests. Have items shipped to: Your Name, Guest at Hotel, [Address]. We\'ll notify you upon arrival.',
    keywords: JSON.stringify(['package', 'delivery', 'shipping', 'mail']),
    priority: 4,
  },
  {
    id: generateId(),
    category: 'service',
    title: 'Wake-Up Calls',
    content: 'Schedule wake-up calls through your in-room phone by pressing the wake-up call button, or request at the front desk. Automated calls or personal calls available.',
    keywords: JSON.stringify(['wake-up', 'alarm', 'morning', 'call']),
    priority: 3,
  },
];

// Verify we have 100 entries
if (demoKnowledgeBase.length !== 100) {
  console.warn(`Warning: Expected 100 knowledge base entries, got ${demoKnowledgeBase.length}`);
}
