/**
 * Demo Tasks
 *
 * Sample tasks for housekeeping, maintenance, concierge, and room service.
 */

import type { NewTask } from '../schema.js';
import { generateId, dateTimeFromNow } from './helpers.js';
import { demoConversations } from './conversations.js';

// Get conversation IDs for linking tasks
const [conv1, conv2, conv3, conv4, conv5] = demoConversations;

export const demoTasks: NewTask[] = [
  // Housekeeping Tasks
  {
    id: generateId(),
    conversationId: conv2?.id, // Linked to the complaint
    source: 'auto',
    type: 'housekeeping',
    department: 'housekeeping',
    roomNumber: '506',
    description: 'URGENT: Room not properly cleaned before guest check-in. Guest complaint - full room cleaning required immediately including fresh linens and towels.',
    priority: 'urgent',
    status: 'in_progress',
    createdAt: dateTimeFromNow(0, 9),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'housekeeping',
    department: 'housekeeping',
    roomNumber: '312',
    description: 'Guest requests extra pillows (2) and hypoallergenic blanket.',
    priority: 'standard',
    status: 'pending',
    createdAt: dateTimeFromNow(0, 8),
  },
  {
    id: generateId(),
    source: 'auto',
    type: 'housekeeping',
    department: 'housekeeping',
    roomNumber: '405',
    description: 'VIP guest - Evening turndown service requested for 7 PM.',
    priority: 'high',
    status: 'pending',
    createdAt: dateTimeFromNow(0, 10),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'housekeeping',
    department: 'housekeeping',
    roomNumber: '218',
    description: 'Deep cleaning required after checkout. Guest reported spillage on carpet.',
    priority: 'standard',
    status: 'completed',
    completedAt: dateTimeFromNow(-1, 14),
    createdAt: dateTimeFromNow(-1, 11),
  },

  // Maintenance Tasks
  {
    id: generateId(),
    source: 'manual',
    type: 'maintenance',
    department: 'maintenance',
    roomNumber: '609',
    description: 'WiFi connectivity issues reported on floor 6. Check access point and signal strength.',
    priority: 'high',
    status: 'in_progress',
    createdAt: dateTimeFromNow(-2, 18),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'maintenance',
    department: 'maintenance',
    roomNumber: '422',
    description: 'Air conditioning not cooling properly. Guest reports room temperature stuck at 75°F.',
    priority: 'high',
    status: 'pending',
    createdAt: dateTimeFromNow(0, 7),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'maintenance',
    department: 'maintenance',
    roomNumber: '315',
    description: 'Bathroom faucet leaking. Slow drip from hot water handle.',
    priority: 'standard',
    status: 'pending',
    createdAt: dateTimeFromNow(0, 6),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'maintenance',
    department: 'maintenance',
    roomNumber: '701',
    description: 'TV remote not working. Replaced batteries but still unresponsive.',
    priority: 'low',
    status: 'completed',
    completedAt: dateTimeFromNow(-1, 10),
    createdAt: dateTimeFromNow(-1, 9),
  },

  // Concierge Tasks
  {
    id: generateId(),
    conversationId: conv3?.id,
    source: 'auto',
    type: 'concierge',
    department: 'concierge',
    roomNumber: '407',
    description: 'Airport shuttle scheduled for 2:30 PM tomorrow. Guest: James Morrison. Destination: Terminal 2.',
    priority: 'standard',
    status: 'pending',
    createdAt: dateTimeFromNow(-1, 16),
  },
  {
    id: generateId(),
    conversationId: conv4?.id,
    source: 'auto',
    type: 'concierge',
    department: 'concierge',
    roomNumber: '407',
    description: 'Restaurant reservation confirmed: The Garden, 8:00 PM tonight, 2 guests (Garcia). Window table requested.',
    priority: 'standard',
    status: 'completed',
    completedAt: dateTimeFromNow(0, 11),
    createdAt: dateTimeFromNow(0, 11),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'concierge',
    department: 'concierge',
    roomNumber: '512',
    description: 'Guest requests theater tickets for tonight\'s 8 PM show. 2 tickets, best available seats.',
    priority: 'high',
    status: 'in_progress',
    createdAt: dateTimeFromNow(0, 9),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'concierge',
    department: 'concierge',
    roomNumber: '608',
    description: 'Arrange birthday cake and champagne for room delivery at 7 PM. Guest celebrating wife\'s birthday.',
    priority: 'high',
    status: 'pending',
    createdAt: dateTimeFromNow(0, 10),
  },

  // Room Service Tasks
  {
    id: generateId(),
    conversationId: conv1?.id,
    source: 'auto',
    type: 'room_service',
    department: 'food_beverage',
    roomNumber: '405',
    description: 'Order: Grilled salmon with vegetables, sparkling water, chocolate mousse. VIP guest - halal preparation required.',
    items: JSON.stringify([
      { name: 'Grilled Salmon with Vegetables', quantity: 1, price: 38 },
      { name: 'Sparkling Water (750ml)', quantity: 1, price: 8 },
      { name: 'Chocolate Mousse', quantity: 1, price: 14 },
    ]),
    priority: 'high',
    status: 'in_progress',
    createdAt: dateTimeFromNow(0, 10),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'room_service',
    department: 'food_beverage',
    roomNumber: '303',
    description: 'Breakfast order for 7:30 AM delivery tomorrow. Full American breakfast x2, orange juice x2, coffee pot.',
    items: JSON.stringify([
      { name: 'Full American Breakfast', quantity: 2, price: 28 },
      { name: 'Fresh Orange Juice', quantity: 2, price: 8 },
      { name: 'Coffee Pot', quantity: 1, price: 12 },
    ]),
    priority: 'standard',
    status: 'pending',
    createdAt: dateTimeFromNow(0, 20),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'room_service',
    department: 'food_beverage',
    roomNumber: '515',
    description: 'Late night snack: Club sandwich, fries, Diet Coke.',
    items: JSON.stringify([
      { name: 'Club Sandwich', quantity: 1, price: 18 },
      { name: 'French Fries', quantity: 1, price: 8 },
      { name: 'Diet Coke', quantity: 1, price: 4 },
    ]),
    priority: 'standard',
    status: 'completed',
    completedAt: dateTimeFromNow(-1, 23),
    createdAt: dateTimeFromNow(-1, 22),
  },

  // IT Support Task
  {
    id: generateId(),
    conversationId: conv5?.id,
    source: 'auto',
    type: 'other',
    department: 'it',
    roomNumber: '609',
    description: 'Deliver portable WiFi hotspot to room. Guest needs for video conference tomorrow.',
    priority: 'high',
    status: 'completed',
    completedAt: dateTimeFromNow(-2, 20),
    createdAt: dateTimeFromNow(-2, 19),
  },

  // Bell Desk Tasks
  {
    id: generateId(),
    source: 'manual',
    type: 'other',
    department: 'bell_desk',
    description: 'Luggage storage: 2 bags for guest Morrison, room 407. Pickup scheduled for 2 PM tomorrow.',
    priority: 'standard',
    status: 'pending',
    createdAt: dateTimeFromNow(-1, 16),
  },
  {
    id: generateId(),
    source: 'manual',
    type: 'other',
    department: 'bell_desk',
    roomNumber: '210',
    description: 'Deliver Amazon package received at front desk to guest room.',
    priority: 'low',
    status: 'completed',
    completedAt: dateTimeFromNow(0, 9),
    createdAt: dateTimeFromNow(0, 8),
  },
];
